---
abstract: 'Helps you paginate, search, sort, and more easily using DBIx::Class'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires:
  Module::Build: 0.35
configure_requires:
  Module::Build: 0.35
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-TraitFor-Controller-DBIC-DoesPaging
requires:
  Carp: 0
  Catalyst::Model::DBIC::Schema: 0.29
  Catalyst::Runtime: 5.80000
  Catalyst::Test: 0
  Catalyst::View::JSON: 0
  DBIx::Class: 0.08108
  FindBin: 0
  JSON: 0
  SQL::Translator: 0.11002
  Test::Deep: 0
  Test::More: 0.88
  parent: 0
resources:
  repository: http://github.com/frioux/Catalyst-TraitFor-Controller-DBIC-DoesPaging
version: 0.093511
